### ISSUE TITLE
Tiny Angular

### ISSUE THREAD

**Issue by timruffles** [eventhandler/london_js_discussions#1]
How small could you make an AngularJS-like framework? Namely, could you get:
- 2-way data-binding MVC
- directives
- testability

into something the size of Backbone?

**Comment by jackfranklin** [comment]
+1 for this as an idea, there's quite a lot to learn from a small Angular like framework thing too - stuff that people see as quite mysterious such as the way Angular does dependency injection would be interesting to demo and see in action.

**Comment by jonathan-fielding** [comment]
+1, would definitely be of interest to know how a small angular like framework works

**Comment by arranrp** [comment]
@timruffles how are you for the 27th of Jan?

**Comment by arranrp** [comment]
Talk booked
