### ISSUE TITLE
Computer science fundamentals for self-taught developers

### ISSUE THREAD

**Issue by codeincontext** [eventhandler/london_js_discussions#7]
Modern developers are able to 'go it alone', by getting on and making software without needing a degree or qualification. My question is whether there are important concepts that are easy to miss if not formally taught.

Things like (top of my head):
- Big O Notation for sorting, searches, etc
- Data structures (linked list, sets, dictionaries etc)
- Normalisation
- bitwise operations
- modelling
- proper terms for things (arity, etc)
- static/dynamic typing
- lexical scoping

I get that some of these are just a part of being a good developer, and that some come with time. Just wondering whether a talk on something like this could benefit people

**Comment by jem-computer** [comment]
Would _love_ this.

**Comment by drtortoise** [comment]
yes yes yes again get @tomstuart

**Comment by tomstuart** [comment]
Off the top of my head, I could give a talk on finite state machines / regular languages / implementing regular expressions etc, based on material from [my book](http://computationbook.com/). Also happy to talk about anything else computer-sciencey if anyone has any requests!

**Comment by Laurian** [comment]
+1 for finite state machines

**Comment by arranrp** [comment]
@tomstuart would you happen to be free on the evening of the 27th of this month?

**Comment by arranrp** [comment]
Booked
